name: 📊 Update GitHub Profile README

on:
  schedule:
    - cron: "0 0 * * *"   # Exécution chaque jour à minuit UTC
  workflow_dispatch:       # Permet de lancer manuellement depuis GitHub Actions
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 🐍 Génération de l’animation Snake
      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: TON-USERNAME
          outputs: dist/snake.svg

      - name: Push Snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
